name: Build NDS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract source
        run: unzip CascadeBlocks.zip -d .
      - name: Build
        run: |
          cd CascadeBlocks
          make
      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: CascadeBlocks-nds
          path: CascadeBlocks/CascadeBlocks.nds
