name: Build NDS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract source
        run: unzip -o CascadeBlocks.zip -d .
      # Install required DS development libraries. The devkitpro/devkitarm image
      # includes dkp-pacman for installing devkitPro packages. Install libnds
      # so that <nds.h> and related headers are available during compilation.
      - name: Install libnds
        run: |
          dkp-pacman -Sy --noconfirm libnds
      - name: Build
        run: |
          cd CascadeBlocks
          make
      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: CascadeBlocks-nds
          path: CascadeBlocks/CascadeBlocks.nds
